stages:
  - triggers

trigger_a:
  stage: triggers
  trigger:
    include: .gitlab/a/.gitlab-ci.yml
  rules:
    - changes:
        - .gitlab/a/*

trigger_b:
  stage: triggers
  trigger:
    include: .gitlab/b/.gitlab-ci.yml
  rules:
    - changes:
        - .gitlab/b/*
